### ISSUE TITLE
URL from demo.py is broken

### ISSUE THREAD

**Issue by kopardev** [sdomanskyi/DigitalCellSorter#4]
Running `demo.py` gave me this error: 

```
% python demo.py
Creating directories:
 data/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.mtx
Downloading file: https://data.humancellatlas.org/project-assets/project-matrices/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.mtx.zip
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    prep.getHCAdataByURL(url, extractPath)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/site-packages/DigitalCellSorter/ReadPrepareDataHCA.py", line 46, in getHCAdataByURL
    urllib.request.urlretrieve(url, os.path.join(os.path.dirname(extractPath), os.path.basename(url)))
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/kopardevn/anaconda3/envs/DCS/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

The URL is broken

```
% wget https://data.humancellatlas.org/project-assets/project-matrices/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.mtx.zip
--2021-06-03 16:55:11--  https://data.humancellatlas.org/project-assets/project-matrices/cc95ff89-2e68-4a08-a234-480eca21ce79.homo_sapiens.mtx.zip
Resolving dtn06-e0 (dtn06-e0)... 10.1.200.242
Connecting to dtn06-e0 (dtn06-e0)|10.1.200.242|:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2021-06-03 16:55:11 ERROR 404: Not Found.
```

Do you know what the new location is?

**Comment by sdomanskyi** [comment]
The data owners have changed the format and location. The complete data can be downloaded from:
https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79/project-matrices

For the sake of demo I uploaded file "data/dfDonorID 085e737d-adb5-4597-bd54-5ebeda170038.h5" to this GitHub repo, and the "demo.py" file is updated to point to this data file. The output results are the same as before.
Note that this is a 50000 cells bone marrow dataset demo, and there is also a small demo on 5000 PBMC. To run small demo install DigitalCellSorter and run in a terminal "python -m DigitalCellSorter".

I hope this helps.

**Comment by kopardev** [comment]
Thanks, @sdomanskyi . I will give this a try.
